#server settings
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: deploy
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

# log4j log level setting
logging.level.kr.ac.jnu.capstone.bigpicture.dongsim: info